### ISSUE TITLE
How to translate a tag, which include a inner tag

### ISSUE THREAD

**Issue by hyliker** [angular-translate/grunt-angular-translate#39]
```
<h1 class="page-title" translate>Start your <span class="text-gold"> Free 10-day Trial</span></h1>
```

**Comment by firehist** [comment]
translate directive will grab all text in current DOM Element, so the key will be 
```Start your <span class="text-gold"> Free 10-day Trial</span>```

**Comment by firehist** [comment]
My bad @hyliker regex will grab 'til first opening `<`
It means for your example, key will be: `Start your`.

It will be hard to maintain if I update all regex to take care of this.
Maybe if others guys ask for that, I'll do the job.
