### ISSUE TITLE
Parser problems

### ISSUE THREAD

**Issue by sebastian-zarzycki** [angular-translate/grunt-angular-translate#41]
With this html code:

`<a ng-if="menuItem.enabled && !menuItem.state && menuItem.url" ng-href="{{ menuItem.url }}" target="_blank" title="{{ menuItem.label | translate }}">{{ menuItem.label | translate }}</a>
`

The result is (with namespacing, but it doesn't matter)

```
{
    "{{ menuItem": {
        "label | translate }}": ""
    },
}
```

I believe this never should fall into parser regex (use only 'KEY' | translate), but above everything else, I've also used delimiter [[ ]] and it still generated this one (delimiter works for other standard extractions).

**Comment by sebastian-zarzycki** [comment]
Echo... echo...

**Comment by SKoschnicke** [comment]
I fixed this problem in my fork, see here:

https://github.com/SKoschnicke/grunt-angular-translate/compare/master...SKoschnicke:dots_in_angular_exps?expand=1

Expressions are still extracted, but the namespacing doesn't break anymore. I think also extracting angular expressions helps to not forget these cases when translating.

**Comment by firehist** [comment]
Done by merge #61.
Thanks a lot @SKoschnicke
