### ISSUE TITLE
Dealing with conditinal (ternary) translation

### ISSUE THREAD

**Issue by forcewill** [angular-translate/grunt-angular-translate#48]
I find my self constantly using translation dependent on some condition like:
`<h3 translate="{{edit ? 'Update' : 'New user'}}" ></h3>`

`grunt-angular-translate` wont be smart about this and extract one single key:
"{{edit ? 'Update' : 'New user'}}"

Is there some way or the possibility improving dealing with this use case ?

Something like http://www.regexr.com/3b7ph

**Comment by bmagic** [comment]
:+1:

**Comment by firehist** [comment]
Thanks for the regex.
It's not as easy as described cause we have to take care to these situations:
```
<h3 translate="{{edit ? 'Update' : 'New user'}}" ></h3>
<h3 translate>{{edit ? 'Update' : 'New user'}}</h3>
<h3>{{edit ? 'Update' : 'New user' | translate}}</h3>
{{ translate_function(edit ? 'Update' : 'New user') }}
<span style="text-align:center" ng-bind-html="edit ? 'Update' : 'New user' | translate"></span>
<h3 title="{{edit ? 'Update' : 'New user' | translate}}"></h3>
```

Please can you review this PR #69
