### ISSUE TITLE
Static translations

### ISSUE THREAD

**Issue by knalli** [angular-translate/grunt-angular-translate#50]
This is question by @mobinni -- reference by https://github.com/angular-translate/angular-translate/issues/1093

----

It would be nice to have the possibility to statically translate Keys in the HTML. An angular-translate build task for Grunt and Gulp if you may. If you need a reference as to what Im talking about:
https://mobinni.io/2015/06/21/quickfire-compiling-angularjs-with-static-translations/
I think so after a short glance at the library. Quick question, does it search for all the translations in HTML

 for instance and generate static HTML, for instance:
```
locales
- nl.json
- en.json
```
After task
```
dist
     - views (en views)
     - nl
        - views (nl views)
```
This so you have base routes to certain translated views?

**Comment by tangorri** [comment]
That would be great !
If so, I would be able to generate 'one dist' language with complete override of all files (identical structure) using sub task ':fr' ':en'

**Comment by firehist** [comment]
Hey there, I'm not sure to get your question @mobini
This task is used to extract `translations keys` from all your source code (JS/HTML) and it's based on regex patterns (so you can extend it as you want).

Please find explanation in [README.md](https://github.com/angular-translate/grunt-angular-translate) and exemples in the [test](https://github.com/angular-translate/grunt-angular-translate/tree/master/test) folder !

**Comment by mobinni** [comment]
My question is if it's possible to create a grunt task maintained by angular-translate to add to its ecosystem to supply this functionality.

**Comment by firehist** [comment]
Think that it's part of an other tools.
This one is an extractor.
