### ISSUE TITLE
The parser get wrong key to table from parsing..

### ISSUE THREAD

**Issue by mikethejet** [angular-translate/grunt-angular-translate#55]
Hi, when parsing html with inserted php code, the parser get this result:

example: 
Parsed file: 
(script tag with contents: ) 

data-require="angular-resource@1.3.10" data-semver="1.3.10" src="<?php echo base_url("assets/bower_components/angular-translate/angular-**translate**.min.js");?>

Get json: 

{
    "\">": "",   
}

Its because of translate word? 
Maybe some regexp can be mofified?
Thank you.

**Comment by firehist** [comment]
Hey @mikethejet.
I clean all issues, so for yours, the problem is not reproducible since the commit `e3ce688419e2b057f501f5ca0605e5e7ac9c0dce`.

Enjoy ;)
