### ISSUE TITLE
Support TRANSLATION_ID provided as element attribute

### ISSUE THREAD

**Issue by dhiraj** [angular-translate/grunt-angular-translate#64]
When translation IDs are supplied in markup in the form:
```html
<ANY translate="TRANSLATION_ID">Default translation</ANY>
```
The translation files are generated like this:
```Javascript
"Default translation":"Default translation"
```
Instead of:
```Javascript
"TRANSLATION_ID":"Default translation"
```

Can support be added for this?

**Comment by alexrada** [comment]
I'm having a similar issue here, couldn't find a fix for it.

**Comment by firehist** [comment]
@alexrada I updated the code, can you take a look @ #68 ?

**Comment by alexrada** [comment]
There will be an error on line 70 if r has length == 2
Same on line 74

if (r.length >= 2) {
...
translationDefaultValue = r[2].trim();

So if r has only 2 elements this will output an error.

**Comment by firehist** [comment]
Yes thanks!
And an other one, I removed the simple `translate` usage :D
