### ISSUE TITLE
Use with ng-repeat

### ISSUE THREAD

**Issue by bmagic** [angular-translate/grunt-angular-translate#75]
Hi, 

I have some issue to extract some keys with angular ng-repeat ...
I use angular ng-repeat with an array of string (['en','fr',...]

```
<select ng-model="form.language">
    <option ng-repeat="language in languages" value="{{language}}"
        {{"LANG_"+language|translate}}
    </option>
</select>
```

I want to have something like : 
LANG_FR:""
LANG_EN:"" 
... 

But I have only one key  ... 
LANG_:""

Do you have any solution to make grunt extract all the KEYS ?

**Comment by rakletadmin** [comment]
We're looking for a similar solution as well. @bmagic how did you end up moving forward?
